# 4.异常

## 在 except 中 return 后还会不会执行 finally 中的代码？怎么抛出自定义异常？

会继续处理 finally 中的代码

用 raise 方法可以抛出自定义异常。

## 介绍一下 except 的作用和用法

except: \#捕获所有异常 

except: &lt;异常名&gt;: \#捕获指定异常 

except:&lt;异常名 1, 异常名 2&gt; : 捕获异常 1 或者异常 2 

except:&lt;异常名&gt;,&lt;数据&gt;:捕获指定异常及其附加的数据 

except:&lt;异常名 1,异常名 2&gt;:&lt;数据&gt;:捕获异常名 1 或者异常名 2,及附加的数据

![](../../.gitbook/assets/image%20%285%29.png)

